apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignosis-node
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: ignosis-node
        image: whoislimshady/ignosis:latest
        ports: 
        - containerPort: 1626
          