apiVersion: v1
kind: Service
metadata: 
  name: ignosis-node
spec: 
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1626
    targetPort: 1626
    nodePort : 31110
